---
- name: ConfigDrive | directories
  file:
    path: '{{ libvirt_images_path }}/{{ libvirt_result_domain_name }}.configdrive/{{ item.key | dirname }}'
    state: directory
  with_dict: libvirt_configdrive_files

- name: ConfigDrive | content
  copy:
    dest: '{{ libvirt_images_path }}/{{ libvirt_result_domain_name }}.configdrive/{{ item.key }}'
    content: '{{ item.value }}'
  with_dict: libvirt_configdrive_files
  register: libvirt_cofnigdrive_result

- name: ConfigDrive | iso image
  command: >
    genisoimage -joliet -rock -volid config-2
    -o {{ libvirt_images_path }}/{{ libvirt_result_domain_name }}.configdrive.iso
    -r {{ libvirt_images_path }}/{{ libvirt_result_domain_name }}.configdrive
  when: libvirt_cofnigdrive_result.changed
