---
- include: domain_id.yml
- include: ssh_port.yml

- include: cloud_image.yml
  when: libvirt_install_type == 'cloud-image'

- include: list.yml
  when: libvirt_all_domains is not defined

- include: create_domain.yml
  when: libvirt_result_domain_name not in libvirt_all_domains

# - include: update.yml
#   when: libvirt_result_domain_name in libvirt_all_domains

- include: autostart.yml

- include: mac_and_ip.yml

- include: port_forward.yml
  protocol: tcp
  source_ip: "{{ libvirt_host_ssh_destination }}"
  source_port: "{{ libvirt_result_ssh_port }}"
  destination_ip: "{{ libvirt_result_ip_address }}"
  destination_port: "{{ libvirt_ssh_guest_port }}"

- include: store_facts.yml

- name: wait for ssh
  wait_for:
    host: "{{ libvirt_host_ssh_ip_address }}"
    port: "{{ libvirt_result_ssh_port }}"
    timeout: 60 # seconds
  delegate_to: 127.0.0.1
  with_items: libvirt_domain_names
