---
- name: ssh_port | extract
  set_fact:
    libvirt_result_ssh_port_generated: >
      {{
        False
          if (libvirt_ssh_port is defined)
            and libvirt_ssh_port
          else
        False
          if (ansible_local is defined)
            and (ansible_local.libvirt_domains is defined)
            and (libvirt_result_domain_name in ansible_local.libvirt_domains)
          else
        True
      }}
    libvirt_result_ssh_port: >
      {{
        libvirt_ssh_port
          if (libvirt_ssh_port is defined)
            and libvirt_ssh_port
          else
        ansible_local.libvirt_domains[libvirt_result_domain_name].ssh_port
          if (ansible_local is defined)
            and (ansible_local.libvirt_domains is defined)
            and (libvirt_result_domain_name in ansible_local.libvirt_domains)
          else
        (ansible_local.libvirt.facts.ssh_port | int) + 1
          if (ansible_local is defined)
            and (ansible_local.libvirt is defined)
            and (ansible_local.libvirt.facts is defined)
          else
        libvirt_ssh_base_port
      }}
