---
- name: create machine id
  command: uuidgen
  register: machine_uuid_result
  when: libvirt_vm_machine_id==''

- name: extract machine id
  set_fact:
    libvirt_vm_machine_id: >
      {{ libvirt_vm_machine_id
      | default(machine_uuid_result.stdout, true)
      | trim }}

- name: extract ssh port
  set_fact:
    libvirt_vm_ssh_port: >
      {{ (ansible_local.libvirt.facts.ssh_port | int) + 1
      if (ansible_local is defined) and ('libvirt' in ansible_local)
      else libvirt_ssh_base_port }}

- name: collect machine facts
  set_fact:
    libvirt_vm_facts:
      ssh_port: "{{ libvirt_vm_ssh_port }}"
