---
- name: create facts folder
  file:
    path: "{{ ansible_facts_path }}"
    state: directory
    recurse: yes

- name: store fact ssh_port
  ini_file:
    dest: "{{ ansible_facts_path }}/libvirt.fact"
    section: "facts"
    option: "ssh_port"
    value: "{{ libvirt_vm_ssh_port }}"

- name: store machines
  template:
    dest: "{{ ansible_facts_path }}/libvirt_machines.fact"
    src: libvirt_machines.j2

- name: re-read facts
  setup:
    filter: ansible_local
