---
- name: facts
  set_fact:
    hooks_folder: "{{ libvirt_host_qemu_machine_hooks_folder }}/{{ ansible_hostname }}"
    real_port_forwards: "{{ lookup('template', '../templates/port_forward_args.json.j2') }}"

- name: create file names
  set_fact:
    managed_files: "{{ lookup('template', '../templates/file_names.j2') }}"

- name: create machine folder
  file:
    dest: "{{ hooks_folder }}"
    state: directory
  delegate_to: "{{ libvirt_hostname }}"

- name: create scripts
  template:
    dest: "{{ hooks_folder }}/{{ manage_name }}_{{ item.source_ip }}-{{ item.source_port }}-{{ item.protocol }}"
    src: 'port_forward.sh.j2'
    mode: 700
  delegate_to: "{{ libvirt_hostname }}"
  with_items: real_port_forwards
  register: create_scripts_result

- name: list existing files
  shell: >
    find
    {{ hooks_folder }}
    -mindepth 1
    -name '{{ manage_name }}_*'
    -type f
    -printf '%P\n'
  changed_when: no
  delegate_to: "{{ libvirt_hostname }}"
  register: existing_files

- name: remove unused files
  file:
    dest: "{{ hooks_folder }}/{{ item }}"
    state: absent
  delegate_to: "{{ libvirt_hostname }}"
  when: item not in managed_files
  with_items: existing_files.stdout_lines

- name: start new files
  command: "{{ item.dest }} start"
  delegate_to: "{{ libvirt_hostname }}"
  when: item.changed
  with_items: create_scripts_result.results
