---
- name: store_facts | facts directory
  file:
    path: "{{ ansible_facts_path }}"
    state: directory
    recurse: yes

- name: store_facts | ubuntu_cloud_image_path
  ini_file:
    dest: "{{ ansible_facts_path }}/libvirt.fact"
    section: "facts"
    option: "ubuntu_cloud_image_path"
    value: "{{ libvirt_images_path }}/{{ libvirt_images_ubuntu_cloud_image_name }}"

- name: store_facts | re-read
  setup:
    filter: ansible_local
