---
- name: download sums and signature
  get_url:
    url: "{{ libvirt_base_vm_url }}/{{ item }}"
    dest: "/tmp/{{ item }}"
    force: yes
  changed_when: no
  with_items:
  - "{{ libvirt_base_vm_sha256sums }}"
  - "{{ libvirt_base_vm_sha256sums_gpg }}"

- name: check GPG keys
  command: 'gpg --list-keys {{ libvirt_base_vm_gpg_keys }}'
  failed_when: no
  changed_when: no
  register: gpg_keys_check

- name: import GPG key
  command: 'gpg --keyserver {{ libvirt_base_vm_gpg_key_server }} --recv-keys {{ libvirt_base_vm_gpg_keys }}'
  when: gpg_keys_check.rc != 0

- name: check and extract signature
  shell: >
    gpg --verify {{ libvirt_base_vm_sha256sums_gpg }} {{ libvirt_base_vm_sha256sums }} &&
    cat {{ libvirt_base_vm_sha256sums }} | grep trusty-server-cloudimg-amd64-disk1.img | cut -f 1 -d " "
  args:
    chdir: "/tmp"
  changed_when: no
  register: extract_signature_result

- name: download image disk
  get_url:
    url: "{{ libvirt_base_vm_url }}/{{ libvirt_base_vm_img }}"
    sha256sum: "{{ extract_signature_result.stdout }}"
    dest: "{{ libvirt_images_path }}/{{ libvirt_base_vm_disk_name_dist }}"
  register: download_result

- name: remove modified image
  file:
    path: "{{ libvirt_images_path }}/{{ libvirt_base_vm_disk_name }}"
    state: absent
  when: download_result.changed

- name: convert the image
  command: "qemu-img convert -O qcow2 {{ libvirt_base_vm_disk_name_dist }} {{ libvirt_base_vm_disk_name }}"
  args:
    chdir: "{{ libvirt_images_path }}"
    creates: "{{ libvirt_images_path }}/{{ libvirt_base_vm_disk_name }}"
  register: convert_image_result

- name: resize image
  command: "qemu-img resize {{ libvirt_base_vm_disk_name }} {{ libvirt_base_vm_disk_size }}"
  args:
    chdir: "{{ libvirt_images_path }}"
  when: libvirt_base_vm_disk_size is defined
    and libvirt_base_vm_disk_size
    and convert_image_result.changed
